name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install global dependencies
      run: |
        npm install -g @ionic/cli
        npm install -g capacitor-resources

    - name: Install project dependencies
      run: |
        npm install
        npm install @capacitor/core @capacitor/cli @capacitor/android

    - name: Add Android platform if missing
      run: |
        npx cap ls | grep android || npx cap add android

    - name: Set up Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Create local.properties for Android SDK
      run: echo "sdk.dir=$ANDROID_HOME" > android/local.properties

    - name: Build Android APK
      run: |
        npm run build
        npx cap sync android
        cd android
        ./gradlew assembleDebug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug.apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
